---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext427
  labels:
    app: BoundedContext427
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext427
  template:
    metadata:
      labels:
        app: BoundedContext427
    spec:
      containers:
        - name: BoundedContext427
          image: username/BoundedContext427:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext970
  labels:
    app: BoundedContext970
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext970
  template:
    metadata:
      labels:
        app: BoundedContext970
    spec:
      containers:
        - name: BoundedContext970
          image: username/BoundedContext970:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext427
  labels:
    app: BoundedContext427
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext427


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext970
  labels:
    app: BoundedContext970
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext970

